### PR TITLE
Fix dark font on dark background by default

### LINKED ISSUE #102: Default theme is dark with dark font
By default the blog displays the dark theme with dark font, only after switching to light theme it works as expected (even when switching back to dark theme).

The dark theme should always use light font to keep things readable.

### PR DESCRIPTION
**Pull request by floscher**
Fixes #102

### CODE REVIEW

File: client/src/util/storage.ts [hunk 1]
```diff
@@ -67,7 +67,17 @@ export function saveCssPreference(css: UserTheme) {
 }
 
 export function loadCssPreference(): UserTheme {
-  return loadFromStorageAsString(window.localStorage, "cssTheme", "lightTheme") as UserTheme;
```
Comment (floscher) [inline client/src/util/storage.ts:70]: The culprit was the default value for UserTheme, which was "lightTheme" instead of "light".

I rewrote this a bit, so Typescript will make sure through the type system that only "light" or "dark" can be returned (also covers cases where some different string is saved in localStorage).

**Review by thooyork — APPROVED** [review]
